### ISSUE TITLE
Position ignored for attributes at ContentType creation

### ISSUE THREAD

**Issue by volarname** [kaliop-uk/ezmigrationbundle#100]
attributes position is ignored and latest item is always on bottom...

**Comment by gggeek** [comment]
Hello.

Is this happening with content that you exported via the 'generate' command, or is it migrations ymls that you are creating by hand ?

**Comment by gggeek** [comment]
So, I took a cursory look at the eZ API.

It seems that the API internally does not support the 'position' attribute of a field definition.
And the migrations bundle so far has neither supported it, nor documented its usage.

Adding support for the 'position' attribute in the yml would indeed be tricky: it could be as simple as an array_sort() for the content creation yml, but definitely more complex for the content update yml.

Morale of the story: I am inclined to declare the `position` attribute unsupported, and actually filter it out from the yml created via the `generate` command.
If you want to change the order of fields, you will have to sort them in the yml.

Is it fine with you?

**Comment by volarname** [comment]
its possible to reorder and rename existing attributtes from multiple ymls migrations without need to remove and add them again?

**Comment by gggeek** [comment]
aha, that's the question I was afraid to ask myself... :-P

**Comment by gggeek** [comment]
Seems I was wrong. I was looking at content creation/update, not content-type. :-O Must be Friday afternoon...

A bit more digging turned up:
- when updating content-type, it is already possible to both reposition fields and rename them (change identifier). It is in the dsl docs of the bundle.
- when creating a content-type, the ez api - as per the docs - does support the 'position' attribute, but the migration code does not.

This issue then goes back to being a valid feature request, to support custom field positioning even at content-type creation time.

I'll try to squish it in in the next release.

**Comment by gggeek** [comment]
Done.

It turns out that supporting all cases (eg. having both fields with and without a specified position) is more painful than expected.

Would you be able to test the current master branch and see that it works for your usecase before I tag a new release ?

**Comment by volarname** [comment]
tested dev-master and it works :+1:
