### ISSUE TITLE
Rename default Migrations folder

### ISSUE THREAD

**Issue by xrow** [kaliop-uk/ezmigrationbundle#101]
Hi,

you noted down you wanted to rename it. I would favor it! I would rename it from MigrationVersions to Migrations or Migration.

https://github.com/kaliop-uk/ezmigrationbundle/blob/master/Resources/config/services.yml#L3

**Comment by gggeek** [comment]
Vote properly accounted for.
This will have to wait for the next major version though.
...in the meantime, you can change it in your own app with just one line in ezpublish/config/some.yml :-)

**Comment by gggeek** [comment]
What would you think about MigrationsDefinitions ? Too long ?

**Comment by xrow** [comment]
> MigrationsDefinitions 

You won`t belive how lazy I am. :-) But MigrationsDefinitions is also not bad. I would let you decide and follow.

**Comment by gggeek** [comment]
Closing as moved to the new project
