### ISSUE TITLE
mode update for type tag

### ISSUE THREAD

**Issue by phibo23** [kaliop-uk/ezmigrationbundle#119]
I wonder why only create and delete were implemented for netgen tags. This restriction prevents us from using migrations for
* updating existing tags
* creating new tags with parents that were created in a previous migration (unless we know the parent's internal id) because we cannot set references to existing tags matched by remote id

**Comment by gggeek** [comment]
Since commit 4999f9adca3ff3c8c6dc5f27da6491d50bd51689 it is possible to load tags and set references to their attributes, which should cover your second case. Will be in 4.1

**Comment by gggeek** [comment]
Tag update added in commit 3a5e2585b9cef0ab3f2b05c1ed147e40d0a5e2d8. Will be in 4.1

**Comment by gggeek** [comment]
PS: feel free to test the master branch before its official tagging :-)

**Comment by phibo23** [comment]
this is great news! 👍 🙂
