### ISSUE TITLE
Missing object states (when managing policy limitations)

### ISSUE THREAD

**Issue by xrow** [kaliop-uk/ezmigrationbundle#122]
Hi,

I have seen that there is not yet support for object states. I might implement it myself if it bothers me too much. This is for now just a reminder. 

https://github.com/kaliop-uk/ezmigrationbundle/blob/master/Core/Helper/LimitationConverter.php

**Comment by gggeek** [comment]
As in: missing CRUD of Object States?

It seems that the ContentManager can already assign them, and we can use them as well for matching...

**Comment by xrow** [comment]
CRUD has the object states.

https://github.com/kaliop-uk/ezmigrationbundle/blob/master/Core/Helper/LimitationConverter.php#L123

I am seeing your have a default case, but amybe that is no goto for obejct state limitations. I need to check a bit more.

**Comment by gggeek** [comment]
Any news on your side ?

**Comment by xrow** [comment]
Not yet ... Backlog...

**Comment by gggeek** [comment]
Note: I added a test for checking that setting the obj state works, and it seem to work as intended:

https://github.com/kaliop-uk/ezmigrationbundle/commit/904f1f19c39b9b34cc19ce7e6d4d5d146bd6e92e

**Comment by gggeek** [comment]
Ping

**Comment by gggeek** [comment]
Long time open with no feedback. Closing
