### ISSUE TITLE
Migration aborted! Error in execution of step 1: Argument '$contentType' has a bad state: Draft of the ContentType already exists in file

### ISSUE THREAD

**Issue by xrowkristina** [kaliop-uk/ezmigrationbundle#138]
Hey,
I have this error during a migrate because we have a draft of the class which we would like to update. Here is the whole output:
```
[xxx@localhost xxx]$ app/console kaliop:migration:migrate --path=app/Migrations/20170720000005_AddContentTypes.yml --no-interaction --env=prod
+---+------------------------------------+-------+
| # | Migration                          | Notes |
+---+------------------------------------+-------+
| 1 | 20170720000005_AddContentTypes.yml |       |
+---+------------------------------------+-------+

=============================================

Processing 20170720000005_AddContentTypes.yml

Migration aborted! Reason: Error in execution of step 1: Argument '$contentType' has a bad state: Draft of the ContentType already exists in file /var/www/sites/fvs/vendor/ezsystems/ezpublish-kernel/eZ/Publish/Core/Repository/ContentTypeService.php line 1037
```
Maybe it would be better if the migration will remove first the drafts of a class and than starts the execution?

Thanks for your help.
Kristina

**Comment by gggeek** [comment]
I will take a look.

Possibly not make draft-cleanup automatic, but make it enabled via a specific yml tag, or even a separate migration step

**Comment by xrowkristina** [comment]
Great, thank you!

**Comment by gggeek** [comment]
Mmm, this might be trickier than expected. It seems that there is no API call in the ContentTypeService to either:

- load drafts created by other users
- remove existing drafts

Even if we extend the ContentTypeService to add the missing functionality, we still would need to extend eZ\Publish\SPI\Persistence\Content\Type\Handler and maybe other classes before we get what we need :-(

**Comment by gggeek** [comment]
See https://jira.ez.no/browse/EZP-28154

**Comment by xrowkristina** [comment]
Thank you for concern this.

**Comment by gggeek** [comment]
Btw, answer from Andre Romke of eZSystems:

> API wise it’s fine:
> content: `deleteVersion`
> contentType: `deleteContentType` and pass it a draft to just delete the draft
> 
> However in both cases when it comes to implementation there is a improvement need to define a policy for allowing a admin for instance to read, edit and delete other peoples drafts

So there is a slight chance that this might be doable.
Will tray to allocate some time to test this out

**Comment by xrow** [comment]
Kristina please report this as a official customer reqwust over the eZ support tracker. Lets see if we can speed this up. :-)

**Comment by gggeek** [comment]
For ContentType/update only: implemented in 4.4

**Comment by ahmed-bhs** [comment]
Any solution about the issue ?

**Comment by gggeek** [comment]
@ahmed-bhs I think your best bet is to follow the ticket https://jira.ez.no/browse/EZP-28154 ...

**Comment by stevecohenfr** [comment]
A way to cleanup contenttype drafts :

```
mysql -uroot -proot cfnews_immo_new -vvv -e "DELETE FROM ezcontentclass WHERE version = 1"
mysql -uroot -proot cfnews_immo_new -vvv -e "DELETE FROM ezcontentclass_attribute WHERE NOT EXISTS (SELECT 1 FROM ezcontentclass WHERE ezcontentclass.id = ezcontentclass_attribute.contentclass_id AND ezcontentclass.version = ezcontentclass_attribute.version)"
mysql -uroot -proot cfnews_immo_new -vvv -e "DELETE FROM ezcontentclass_attribute_ml WHERE NOT EXISTS (SELECT 1 FROM ezcontentclass_attribute WHERE ezcontentclass_attribute.id = ezcontentclass_attribute_ml.contentclass_attribute_id AND ezcontentclass_attribute.version = ezcontentclass_attribute_ml.version)"
mysql -uroot -proot cfnews_immo_new -vvv -e "DELETE FROM ezcontentclass_classgroup WHERE NOT EXISTS (SELECT 1 FROM ezcontentclass WHERE ezcontentclass.id = ezcontentclass_classgroup.contentclass_id AND ezcontentclass.version = ezcontentclass_classgroup.contentclass_version)"
mysql -uroot -proot cfnews_immo_new -vvv -e "DELETE FROM ezcontentclass_name WHERE NOT EXISTS (SELECT 1 FROM ezcontentclass WHERE ezcontentclass.id = ezcontentclass_name.contentclass_id AND ezcontentclass.version = ezcontentclass_name.contentclass_version)"
```
