### ISSUE TITLE
fields not removed when updating contentTypes

### ISSUE THREAD

**Issue by Specthram** [kaliop-uk/ezmigrationbundle#141]
Hello there,
When i update my contentTypes with the command : `app/console kaliop:migration:migrate`, the new fields are correctly added, but the old ones are not removed (they are not defined in the yaml file).
Or maybe I missed something ?
Thank you :)

**Comment by blankse** [comment]
At the moment you must set these field identifier to the remove_attributes setting.
See here: https://github.com/kaliop-uk/ezmigrationbundle/blob/master/Resources/doc/DSL/ContentTypes.yml#L174

With my PR (https://github.com/kaliop-uk/ezmigrationbundle/pull/127) it is possible to set these setting to * and remove all fields, that are not available in the update step.

**Comment by gggeek** [comment]
@blankse sorry for not acting on your upsert PRs, too many things in my backlog to carve enough time for such a complex issue.

In the meantime, if you would be so kind to send a separate PR for only the '*' support for the remove_attributes setting, I might be able to push out a new release next weekend...

**Comment by Specthram** [comment]
Thank you for your answers ! It will do the job for me, and the PR seems to great too. I just hope it keep fields ID's to prevent data lost.

**Comment by gggeek** [comment]
Sure, nothing of existing fields is modified.

As a side note: even without this PR, you can already remove existing fields: you just have to specify them one by one using the `remove_attributes` tag in your yml

**Comment by gggeek** [comment]
PS: at the moment the Travis tests fail. I am almost sure that this is not related to the introduction to the new code, but rather to eZSystems having introduced a subtle bug in kernel 6.7.6. See the comment I left at https://jira.ez.no/browse/EZP-28148?focusedCommentId=218615&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-218615

**Comment by gggeek** [comment]
Implemented in 4.4
