### ISSUE TITLE
"The helper 'table' is not defined" (v4.3.0 + ezplatform 1.12 + symfony v3.3.10)

### ISSUE THREAD

**Issue by storton** [kaliop-uk/ezmigrationbundle#143]
Hi,
I'm running this bundle v4.3.0 + ezplatform 1.12 + symfony 3.3.10.
Commands "kaliop:migration:status" and "kaliop:migration:migrate" crash and throw the folllowing exception:
[Symfony\Component\Console\Exception\InvalidArgumentException]: The helper "table" is not defined. 

(command "kaliop:migration:generate" works fine)

Some more details here:
https://discuss.ezplatform.com/t/kaliop-migrationbundle-error-thrown-while-running-command/148

Thank you

**Comment by gggeek** [comment]
Fixed in 4.4
