### ISSUE TITLE
No active transactions on CircleCi

### ISSUE THREAD

**Issue by plozmun** [kaliop-uk/ezmigrationbundle#156]
Hi , I have a issue on CircleCi. Migrations works on local and production but in CircleCi it shows the following error after clean install.

```
Migration failed! Reason: Error in execution of step 2: Error post migration execution in file ..vendor/ezsystems/ezpublish-kernel/eZ/Publish/Core/Repository/Repository.php line 974: There is no active transaction.
There is no active transaction.
There is no active transaction.
There is no active transaction.
```
Do you know what it could be?

**Comment by gggeek** [comment]
Hello.

The funny thing is: I also have the same error messages on some prod environments (GCP iirc). The dev servers for the same project do not have any problems.

So far I did not have enough time to investigate deeply.

However the good thing is that, at least for my case, all the migrations that were showing that message did in fact work as expected. The error comes from the code of the migration bundle that gets upset when it tries to commit at the end of the whole process and finds that there is no transaction to commit any more. Which means most likely that someone else just committed.
So more of an annoyance than a real problem.

Btw, do you know which type of database is used on CircleCi? Is it possible that it is based on Galera replication ?

**Comment by plozmun** [comment]
I'm using image circleci/mysql:5.7 . You're right. Looks like migrations works. I'll use --ignore-failures to ignore these errors :)

Thank you!

**Comment by plozmun** [comment]
It was my fault. I had a service that needed an outside service and failed in the autowire. 😅 

Closing! Thanks!
