### ISSUE TITLE
Doc typo in command for applying single migration

### ISSUE THREAD

**Issue by blankcheck** [kaliop-uk/ezmigrationbundle#158]
This

`php ezpublish/console kaliop:migration:migrate --path=src/MyNamespace/MyBundle/MigrationsVersions/20160803193400_a_migration.yml`

should be this
`
php ezpublish/console kaliop:migration:migrate --path=src/MyNamespace/MyBundle/MigrationVersions/20160803193400_a_migration.yml`

There is extra s in MigrationsVersion ;)

**Comment by gggeek** [comment]
Thx, fixed :-)
