### ISSUE TITLE
Method declarations in Matchers

### ISSUE THREAD

**Issue by amauryvallier** [kaliop-uk/ezmigrationbundle#179]
With the newly installed 5.7.0 version, I get this warning whenever I try to clear the cache of my project :

`Warning: Declaration of Kaliop\eZMigrationBundle\Core\Matcher\ContentVersionMatcher::matchAnd(array $conditionsArray, $content) should be compatible with Kaliop\eZMigrationBundle\  
  Core\Matcher\AbstractMatcher::matchAnd($conditionsArray)`

There seems indeed to be a discrepancy between those methods:
- https://github.com/kaliop-uk/ezmigrationbundle/blob/master/Core/Matcher/AbstractMatcher.php#L36
- https://github.com/kaliop-uk/ezmigrationbundle/blob/master/Core/Matcher/ContentVersionMatcher.php#L110

I don't really know what you would think is the best way to solve it, so I didn't make a PR, but I also found out that the method matchOr will face the same problem.

Tested with PHP 7.1 & ezpublish-kernel v7.3.4

**Comment by gggeek** [comment]
Thx for letting me know.
The fix should be pretty straightforward: change `ContentVersionMatcher::matchAnd(array $conditionsArray, $content)` to `ContentVersionMatcher::matchAnd($conditionsArray, $content = null)` (and add a check for $content not being null in code).
If you can test that, I should be able to push out 7.0.1 quite quickly

**Comment by crevillo** [comment]
is there a pull request for this @amauryvallier 
@gggeek should we throw an exception in case content is null? 
i can work in the pr if you want, guys.

**Comment by gggeek** [comment]
I think that we should throw if $content is null.
Wouldnt say no to a PR :-)

**Comment by amauryvallier** [comment]
I'll make a pull request right now.

**Comment by crevillo** [comment]
Great!

**Comment by amauryvallier** [comment]
With the PR merged, I think we can close this issue.

**Comment by crevillo** [comment]
@gggeek do you plan to tag this fix soon?

**Comment by crevillo** [comment]
@gggeek looks we need to reopen this. i've just updated and got the error again
```
Package operations: 0 installs, 1 update, 0 removals
  - Updating kaliop/ezmigrationbundle (5.6.0 => 5.7.1): Downloading (connecting.Downloading (100%)         
Package guzzle/guzzle is abandoned, you should avoid using it. Use guzzlehttp/guzzle instead.
Package symfony/assetic-bundle is abandoned, you should avoid using it. Use symfony/webpack-encore-pack instead.
Writing lock file
Generating autoload files
ocramius/package-versions:  Generating version class...
ocramius/package-versions: ...done generating version class
> Incenteev\ParameterHandler\ScriptHandler::buildParameters
Updating the "app/config/parameters.yml" file
> eZ\Bundle\EzPublishCoreBundle\Composer\ScriptHandler::clearCache

In ContentVersionMatcher.php line 12:
                                                                               
  Warning: Declaration of Kaliop\eZMigrationBundle\Core\Matcher\ContentVersio  
  nMatcher::matchAnd(array $conditionsArray, $content = NULL) should be compa  
  tible with Kaliop\eZMigrationBundle\Core\Matcher\AbstractMatcher::matchAnd(  
  $conditionsArray)                                                            
                                                                               

Script eZ\Bundle\EzPublishCoreBundle\Composer\ScriptHandler::clearCache handling the symfony-scripts event terminated with an exception

                                                                               
  [RuntimeException]                                                           
  An error occurred when executing the "'cache:clear --no-warmup'" command:    
                                                                               
                                                                               
                                                                               
                                                                               
  In ContentVersionMatcher.php line 12:                                        
                                                                               
                                                                               
    Warning: Declaration of Kaliop\eZMigrationBundle\Core\Matcher\ContentVers  
  io                                                                           
    nMatcher::matchAnd(array $conditionsArray, $content = NULL) should be com  
  pa                                                                           
    tible with Kaliop\eZMigrationBundle\Core\Matcher\AbstractMatcher::matchAn  
  d(                                                                           
    $conditionsArray)                              ```

as abstract matchaAnd has no array typehinted, maybe we need to avoid that typehint in the extending class too...

**Comment by amauryvallier** [comment]
Weird, I did not have this error after the first correction, but now I've reproduced it.

To be thorough but also consistent, I think we should add the array typehint on the AbstractMatcher method since it is the only place it seems to be missing? I'll add a PR for that.

**Comment by gggeek** [comment]
Attempted a new fix, released as 5.7.2

**Comment by amauryvallier** [comment]
Well, with the 5.7.2 I have now a warning on the matchOr function but only when I launch a migration command. Warning below:

`Warning: Declaration of Kaliop\eZMigrationBundle\Core\Matcher\ContentVersionMatcher::matchOr($conditionsArray, $content = NULL) should be compatible with Kaliop\eZMigrationBundle\Core\Matcher\AbstractMatcher::matchOr(array $conditionsArray)`

**Comment by gggeek** [comment]
Let's see if I get it right with 5.7.3...

**Comment by gggeek** [comment]
No feedback?

**Comment by amauryvallier** [comment]
Sorry about the lack of feedback! I haven't experienced this bug since the 5.7.3, that seems to be good! :+1: 

Thanks a lot for everything!
