### ISSUE TITLE
Ability to use `-a` flag for `kaliop:migration:generate`

### ISSUE THREAD

**Issue by jdcrecur** [kaliop-uk/ezmigrationbundle#187]
As discovered and reported on this issue: https://github.com/kaliop-uk/ezmigrationbundle/issues/185

When removing the default ez admin user this breaks the default behavior of ezmigrationbundle; it expects by default to be able to use the admin user of id 14 (not just the username "admin").

As discovered with the help of @gggeek this can be bypassed with passing the `--admin-login` flag (`-a`). 

The same however is not true for generating new migration files based on existing content types, as a result without the admin user of id 14 it is not possible to generate these files.

The workflow for our  php developers is to create or change a content type via the ezadmin then export once final to the migration yaml file.

(as a possible feature enhancement, to even place some of the config into a symfony config file)

**Comment by gggeek** [comment]
This is now in master, will be out most likely next week.
Testing would be appreciated.

**Comment by jdcrecur** [comment]
Hi @gggeek 

Just gave this a whirl  and looks to be working great :) thanks for the update!

John

**Comment by gggeek** [comment]
Fixed in 5.8.0
