### ISSUE TITLE
Generate Language Type

### ISSUE THREAD

**Issue by raupie** [kaliop-uk/ezmigrationbundle#194]
Is it possible to dump the existing languages into a migration file? 

`bin/console kaliop:migration:generate --type=language --match-type=all AppBundle` is how I would imagine this would work. 

Maybe I'm missing something and it already does this. Where can I find a list of available '--types='?

**Comment by gggeek** [comment]
Hello.
At the moment it is not possible to list all 'generatable' entities. However you can look in the code for the classes which implement the `MigrationGeneratorInterface` interface.
Being able to list all of the available ones looks like a good feature request. Care to open a separate ticket for that?

**Comment by gggeek** [comment]
Ps: at the moment the list of available types of migrations to generate is given to you by the help text of the 'generate' command

**Comment by gggeek** [comment]
Implemented, will be in the next release
