### ISSUE TITLE
Add support for listing 'generatable' entities

### ISSUE THREAD

**Issue by raupie** [kaliop-uk/ezmigrationbundle#195]
See #194 

The `--help` only gives a brief sampling of how to generate an entity. It would be helpful to know what kind's of entities can be generated. Such as non content types like languages etc. 

Basically need to know what are the available options this flag accepts. `--type=`.

**Comment by gggeek** [comment]
To be complete, for each type we should as well list available values for the 'match-type' flag...

**Comment by gggeek** [comment]
Implemented, will be in next release
