### ISSUE TITLE
resolve reference on role/create identifier

### ISSUE THREAD

**Issue by dannyniedziella** [kaliop-uk/ezmigrationbundle#196]
Hi,
for now it is not possible to use a reference when creating a new role. This should be useful when using loops for creating multiple roles.

        -
            type: role
            mode: create
            name: "[reference:ROLENAME]"

Missing resolve in Core/Executor/RoleManager.php:38
        $roleCreateStruct = $roleService->newRoleCreateStruct($step->dsl['name']);

Greets
Danny

**Comment by gggeek** [comment]
Implemented (as well as in role/update). Will be in next release
