### ISSUE TITLE
Extend the generation of migration files ?

### ISSUE THREAD

**Issue by StarNab** [kaliop-uk/ezmigrationbundle#204]
Hi,

Is it possible to extend the migration file process generation ? 
I'm using "kaliop:migration:generate" and I want to customize the remote_id in the YML file generated. Can this be achieved at the moment ? Is there an event-like solution for that for example ?

**Comment by StarNab** [comment]
Hi @gggeek , yes I thought about that. In my case as I just wanted to customize the remote_id, it felt it was overkill. I might make a pull request later on then :)

**Comment by gggeek** [comment]
Implemented in master
