### ISSUE TITLE
Reference conflict between migrations execute in the same "migrate" command

### ISSUE THREAD

**Issue by Petitmur** [kaliop-uk/ezmigrationbundle#206]
It's is possible to isolate references of each migrations files to avoid conflict with references of others migration files ?
Maybe, to have the possibility to import a file of reference if needed.

**Comment by gggeek** [comment]
There is a comma-line flag that can be used to run each migration as a separate php process. This way, the references get naturally confined to the migration that defines them

**Comment by gggeek** [comment]
Also, there is a migration step available that can be used to import/export references to files
