### ISSUE TITLE
java.lang.NegativeArraySizeException SOLR multi core error

### ISSUE THREAD

**Issue by SerheyDolgushev** [kaliop-uk/ezmigrationbundle#207]
`2147483647` limit is `causing java.lang.NegativeArraySizeException` if you have multiple cores

**Comment by SerheyDolgushev** [comment]
`2147483647` limit is causing `java.lang.NegativeArraySizeException` if you have multiple cores

**Comment by gggeek** [comment]
Added a workaround by making the value used as query limit a parameter.
Documented in the FAQ section of the README.
The process to set the correct value to the parameter is left to the developer.

Is that ok or do you envision a better approach/solution?

**Comment by gggeek** [comment]
Implemented in 5.10

**Comment by SerheyDolgushev** [comment]
I was thinking about something like:
```
$this->queryLimit = floor(self::INT_MAX_16BIT/SOLR_CORES_COUNT);
```

But query limit options sounds also like a good solution for this kind rare cases.

**Comment by gggeek** [comment]
That would also work, with the caveat of having most likely to check if that constant is defined before using it - and trusting that it will always be there and used for the desired purpose (eg. there's lots of renaming going on in the latest ezplatform version atm, so I am not 1000% sure about that going forward...).
Also, using a parameter is slightly more cumbersome for the developer, but it gives her more flexibility if any special cases arise in the future.
