### ISSUE TITLE
Cannot unassign a group from a role

### ISSUE THREAD

**Issue by korsarNek** [kaliop-uk/ezmigrationbundle#211]
kaliop/ezmigrationbundle: 5.9.3

In the DSL documentation, it is written that it is possible to unassign a group from a policy. This doesn't seem to work.
https://github.com/kaliop-uk/ezmigrationbundle/blob/48a65b89906abd74fc2a2cebdaf97dab8f3f85c0/Resources/doc/DSL/RolesAndPolicies.yml#L122

I checked the code in the RoleManager and couldn't find any code about unassigning, but there seems to be some in the UserManager. I could use that as an alternative for now.
In the RoleManager code I also found that it is possible to set a new name via "new_name", which is not mentioned in the DSL.

**Comment by gggeek** [comment]
Indeed. I am fixing the doc first, as it seems that this was never supported - there was some code in old versions (at least up to 2.0) that was never called and at some point got removed in cleanups.
The core eZP api should allow us to reintoduce this feature.

**Comment by gggeek** [comment]
You are also correct about 'new_name' - even though for the sake of uniformity, I'd like to rename that field simply to `name` going forward...

**Comment by gggeek** [comment]
Implemented in 5.10
