### ISSUE TITLE
Support eZPlatform 3.0

### ISSUE THREAD

**Issue by gggeek** [kaliop-uk/ezmigrationbundle#218]
Note: will have to decide if we use a separate branch, a separate repo, or manage to keep it all working in a single branch...

**Comment by gggeek** [comment]
Note 2: at the moment support for eZPlatform 3 is being explored in a dedicated branch.

Current status is: the 3.0-beta1 release of ezplaftorm is inconsistent and does not allow us to properly test (errors given by the services provided by the different packages not being in sync)

**Comment by xrow** [comment]
@gggeek Hi Gaetano, do you plan any work on this issue for the next time? Currently 3.0 stable is out.

**Comment by gggeek** [comment]
Hi. I do plan to work on this, but it probably won't be out in the very short term.

a) there are still a fair amount of bugs and features that I want to push into the 'v2' branch, before the v3 branch gets officially split off. At least two 5.x point releases, maybe more;

b) after that, I plan to 1. review all PRs that have been merged here, and 2. implement quite an amount of breaking changes to the API (since eZPlatform went for introducing a huge amount of BC breakage this time around, it feels like a good time to do the same here)

So don't hold your breath. And you can forget having the same migration defs working for v1-v5 and v6 (of course feel free to complain loudly about this last point if you have a valid usecase)

**Comment by ajakov** [comment]
Hey @gggeek would you maybe have some tips for anyone wanting to contribute to this branch?

I need it working on 3.1 version, so if I find some time and get lucky enough I might send some pull requests. I managed to get it to install, but that's it so far.

**Comment by gggeek** [comment]
@ajakov tahnks for the offer.
I have picked up this week work on 'getting all features and bugfixes out of the door' for the 5.x branch. As soon as that is done, I'll start working on ezmb 6, which will support ezplatform 3. At the moment, I don't even know how far the thing is from working, tbh... Also, I have plans for grand changes, but those are either not yet cast in stone or not written down in specs clear enough for someone else to read.
I'll surely ping you when there is something more definite to work on.

**Comment by gggeek** [comment]
Closing as moved to the new project

**Comment by gggeek** [comment]
For anyone interested: I started development of the new version at https://github.com/tanoconsulting/ezmigrationbundle2
