### ISSUE TITLE
Support Enterprise Edition

### ISSUE THREAD

**Issue by plozmun** [kaliop-uk/ezmigrationbundle#219]
Hi! 

Enterprise edition is supported? I have try with reference like 
https://github.com/ezsystems/ezplatform-ee-demo/blob/v2.5.2/src/AppBundle/MigrationVersions/landing_page_tests.yml#L64
but it seems is not working properly.

Thanks

**Comment by gggeek** [comment]
Hello.

In general, EE should be working just as good as CE.

However,
- it is not possible to run tests on Travis against eZPlatform EE
- I have not looked up how hard it would be to selectively enable in the MigrationBundle support for those fieldtypes which are only in EE (without breaking or making cumbersome CE installs)

Also, the only project which I personally work on at the moment based on EE is still on eZPublish 5.4, so I can not easily test on existing setups.

This is why I have not merged in Prs such as #153.

I assume that the code that you linked to should be working, but if it is not, you are probably better off asking to the developers who wrote that.

I'd be happy to better support EE, but at the moment this means getting some support either from the eZ community or eZSystems themselves...

**Comment by plozmun** [comment]
Yeah, I figured it was hard to test that, thanks anyway.

**Comment by gggeek** [comment]
Maybe creating a separate bundle, which would get less testing guarantees, would be an acceptable solution?

**Comment by plozmun** [comment]
Maybe it's a good idea but I don't know if it's worth the effort if there aren't many people using it.
