### ISSUE TITLE
Add support for ezcountry field value set as a single string

### ISSUE THREAD

**Issue by gggeek** [kaliop-uk/ezmigrationbundle#224]
Eg: allow a field of type ezcountry to have its value set by specifying in the migration simply 'IT' or 'ES' as value ( currently it works if we pass an array: [ 'ES' ] )

**Comment by crevillo** [comment]
we should allow to add an array of codes in the case the field allow multiple values. 
i'm working on it...

**Comment by gggeek** [comment]
Merged - will be in release 5.13
