### ISSUE TITLE
Migration kaliop / eztags

### ISSUE THREAD

**Issue by fanchoop** [kaliop-uk/ezmigrationbundle#230]
Hello, 

J'ai deux dossier avec des tags differents dans ces dossiers.

Je souhaite lors de la création d'un contenu "article" (ezplatform). Avoir deux champs ou je puisse rajouter un tag (un par dossier). 

or aujourd'hui je peux rajouter n'importe quel tag des deux dossiers. et moi je veux avoir un dossier tags défini pour chacun des deux champs. Est-ce bien dans le Validator-configuration que je dois spécifier ceci ? 

merci de votre aide 

```
-
  type: content_type
  mode: update
  match:
    contenttype_identifier: article
  attributes:
    -
      identifier: interest
      type: eztags
      name:
        fre-FR: "Interêts"
      description: {  }
      required: false
      searchable: true
      info-collector: false
      disable-translation: false
      category: content
      position: 15
      field-settings: {  }
      validator-configuration:
        TagsValueValidator: { maxTags: 3 }
    -
      identifier: activity
      type: eztags
      name:
        fre-FR: "Activités"
      description: {  }
      required: false
      searchable: true
      info-collector: false
      disable-translation: false
      category: content
      position: 15
      field-settings: {  }
      validator-configuration:
        TagsValueValidator: { maxTags: 3 }
```

**Comment by gggeek** [comment]
Iirc cela depends de la version de eztags utilisee (certains parametres ayant change' de mode de configuration). Quelle versions de eZPlatform et eZTags sont en jeu?

**Comment by fanchoop** [comment]
Ez platform 2.5 et netgen/tagsbundle : 3.4.

**Comment by fanchoop** [comment]
ok with sebTreeLimit, i find thank's
