### ISSUE TITLE
Resolverinterface

### ISSUE THREAD

**Issue by ds-arithnea** [kaliop-uk/ezmigrationbundle#232]
- PHP 7.4
- "kaliop/ezmigrationbundle": "^5.9",

EmbeddedRegexpReferenceResolverTrait.php

Has a wrong method signature:

abstract **protected** function getReferenceValue($stringIdentifier);

should be:

abstract **public** function getReferenceValue($stringIdentifier);

eZ\Bundle\EzPublishCoreBundle\Composer\ScriptHandler::clearCache
PHP Fatal error:  Access level to Kaliop\eZMigrationBundle\Core\ReferenceResolver\EmbeddedRegexpReferenceResolverTrait::getReferenceValue() must be public (as in class Kaliop\eZMigrationBundle\Core\ReferenceResolver\PrefixBasedResolver) in [...]/vendor/kaliop/ezmigrationbundle/Core/ReferenceResolver/AbstractResolver.php on line 89

**Comment by ds-arithnea** [comment]
Any Feedback on this?

**Comment by gggeek** [comment]
Sorry, I have been quite busy lately. I hope to have time to give some love to this bundle starting next week...

**Comment by gggeek** [comment]
Fixed in version 5.10.2
