### ISSUE TITLE
Allow migration generation command to specify a directory, not only a bundle

### ISSUE THREAD

**Issue by gggeek** [kaliop-uk/ezmigrationbundle#38]
The codebase and the status command now support it, but not the generation one.

We could f.e. look for th presence of the / char in the 1st argument to tell apart bundles from paths...

**Comment by gggeek** [comment]
When we allow creation fo migrations in custom paths, we could as well make the  bundle look in /app and /ezpublish by default besides the bundles directories

**Comment by gggeek** [comment]
Implemented; by looking for presence of a / char in the path. No looking in any special folder by default

**Comment by nicosomb** [comment]
Hello @gggeek.

Thank you for this bundle. 
I don't know how I can generate a new migration in `app/migrations` for example. 
I tried this command: 

`bin/console kaliop:migration:generate app/migrations MyMigration --format=sql`

But it failed (`Bundle 'app/migrations' does not exist or it is not enabled.`). 

Could you explain how I can do please?

**Comment by gggeek** [comment]
is app/migrations an existing directory before you run the command ?

**Comment by nicosomb** [comment]
The directory needs to exist, I saw it just after.
