### ISSUE TITLE
Add support for mass content creation 

### ISSUE THREAD

**Issue by gggeek** [kaliop-uk/ezmigrationbundle#46]
It would be nice if the extension provided some kind of 'lorem ipusm' functionality.

For that, it would need, at a minimum to:
- support for content creation a 'repeat' tag
- have a reference resolver which generates random text (and do late-binding for its values)

Queued for v2 of yml spec

**Comment by gggeek** [comment]
We would also need to
- make sure that a "huge" migration yml can be executed without memory leaks
- possibly have a way to disable signal-slots for speed of execution

**Comment by crevillo** [comment]
big +1 for this one.

**Comment by crevillo** [comment]
> possible have a way to disable signal-slots

maybe using repository core instead? ;)

**Comment by gggeek** [comment]
NB: a new bundle is in the works for this: https://github.com/kaliop-uk/ezloremipsumbundle

Some of the required functionality will be part of migration bundle 4.8

**Comment by gggeek** [comment]
eZLoremIpsumBundle is now at release 1.2 and working ok for anything less than 'huge size content creation'. Will migrate to there requests to better support huge datasets.
