### ISSUE TITLE
Allow to save and load references between migrations

### ISSUE THREAD

**Issue by gggeek** [kaliop-uk/ezmigrationbundle#51]
This makes it easy to execute separate migrations which deal with the same set of objects.

Currently, it is possible only as long as the separate migrations are executed within the same 'migrate' command.

**Comment by gggeek** [comment]
Code for setting/loading migrations merged.
Code for saving them will need to wait until version 4.0, as it will involve a BC break of an interface

**Comment by maxbaldanza** [comment]
Hi @gggeek,
This sounds like a very useful feature. Is there any documentation or a PR I can look at that adds this? Struggling to find how to implement this at the moment.
Thanks

**Comment by gggeek** [comment]
Well, it is already in. Just use the the latest 4.0 rc :-)

**Comment by gggeek** [comment]
https://github.com/kaliop-uk/ezmigrationbundle/blob/master/Resources/doc/DSL/References.yml

**Comment by maxbaldanza** [comment]
Thank you so much, I didn't see the `load` mode for references. That is a super helpful feature 👍 
`save` looks useful too 😄
