### ISSUE TITLE
Fatal error when creating content (and a few more operations) with delayedindexing disabled

### ISSUE THREAD

**Issue by gggeek** [kaliop-uk/ezmigrationbundle#53]
The problem is due to the fact that db changes done by the migration executor are wrapped in a transaction, and that in 2014.3 the legacy stack uses a separate database connection from the ez5 stack.

The result is that, when content is created via a migration, the legacy stack tries to send it to the indexation engine, but fails because it does not 'see' the content at all in the database.

A possible fix would be to disable usage of transactions completely, but that would introduce more problems than it solves.

Another fix could involve setting up a custom signal listener which would do the db commit before firing the legacy indexation code...

...or we could stop supporting 2014.3 altogether, as it is slightly buggy and will most likely not see any fixes in the future

**Comment by crevillo** [comment]
i'd vote for 3... or for 2 if 3 is too drastic.

**Comment by gggeek** [comment]
I will at least document it in the readme

**Comment by gggeek** [comment]
Further analysis reveals that
- this problem happens as well with eZP 2014.11 and delayedindexing off
- apart from content creation, it also affects adding and removing locations, updating users and a few more operations ( we can look for all the Slot classes which call eZContentOperationCollection::registerSearchObject, eZContentObject::fetch or eZContentObjectTreeNode::fetch )

So a proper fix is definitely needed

**Comment by gggeek** [comment]
Workaround put in place for the moment: allow (via cli switch) to disable wrapping migrations in transactions

**Comment by gggeek** [comment]
let's call it fixed :-)
