### ISSUE TITLE
Content create should be able to return subtree path

### ISSUE THREAD

**Issue by wizhippo** [kaliop-uk/ezmigrationbundle#67]
With out being able to get a subtree path reference for created content you cannot assign a role to a user with a subtree limitation to the created content.

**Comment by gggeek** [comment]
by subtree path you mean the Location::pathString of the created content?

**Comment by wizhippo** [comment]
Yes. That would be handy

**Comment by gggeek** [comment]
Done in 2.1.0. Please Test :-)

**Comment by wizhippo** [comment]
Works great thank you.

**Comment by SalvatorePollaci** [comment]
@wizhippo @gggeek Creating a reference containing a content's path works correctly. The problem is that ezmigration does not allow to create a subtree limitation using a reference, i.e. one must specify the subtree path manually, making the subtree reference useless.

```
https://github.com/kaliop-uk/ezmigrationbundle/blob/master/Resources/doc/DSL/RolesAndPolicies.yml#L48
```

```
#  Subtree limitation example:
#  identifier: Subtree
#  values: [/1/2/3/4, /1/2/3/15] # List of subtree path strings, needs to be the location path
```
