### ISSUE TITLE
[Feature] Ability to run migration without tracking

### ISSUE THREAD

**Issue by wizhippo** [kaliop-uk/ezmigrationbundle#73]
It would be great if we could run a specific migration file without tracking it.  This would be handy as a migration could be used as a template or 'import' to add a site structure for example to the repository that does not need to be tracked.

**Comment by gggeek** [comment]
Can you elaborate a bit on the usecase? I am not sure I get the need to 'not track' the executed migration.
Fe. a 'template' migration should never be executed, imho. If it is executed by mistake, it is good that we track it.
Otoh you can already remove a migration from the db after having executed it, if what you are doing is playing around with its definition...

As for not tracking, there are 2 aspects to consider:
1. do not have the migration listed for execution (in case of eg. a template) => can be achieved by putting the migration file in a separate folder
2. do not add the migration to the db when executing it => the caveat here is that, if it fails, we do not give on the command line the same output that we store in the db. If we are running an 'untracked' migration otoh it is very important to give that output immediately to the user, so there would need to be some changes in the API of the migration service...

**Comment by wizhippo** [comment]
I guess I'm abusing the bundle.  I was going to use it to import generated items on the fly.  Just as easy to do it via the api instead.  I've closed this request.

**Comment by gggeek** [comment]
Yup if you can get it working via api call to the servuce then we can call
it quit. If ypu meed a better api to the service just let me know
