### ISSUE TITLE
show content field validation error details

### ISSUE THREAD

**Issue by phibo23** [kaliop-uk/ezmigrationbundle#84]
when creating content and a validation error occurs, only a very vague message is shown:

```
Migration aborted! Reason: Error in execution of step 4: Content fields did not validate in file /path/to/project/vendor/ezsystems/ezpublish-kernel/eZ/Publish/Core/Repository/ContentService.php line 629
```

I tried adding `eZ\Publish\API\Repository\Exceptions\ContentFieldValidationException` in https://github.com/kaliop-uk/ezmigrationbundle/blob/master/Core/MigrationService.php#L318 but that lead to some errors and I currently don't have time to look into it.

**Comment by gggeek** [comment]
Thx will look into it

**Comment by crevillo** [comment]
@gggeek that error message isn't coming from eZ Publish kernel itself? It's vague there too...

**Comment by phibo23** [comment]
@crevillo yes that's the message string from the kernel exception, but a validation exception has additional `getFieldErrors` which the function I linked tries to add to the output. except it doesn't do it for `ContentFieldValidationException` ^^

**Comment by gggeek** [comment]
Fixed. Will be in upcoming 3.0 (either final or beta7)
