### ISSUE TITLE
Documentation for how to migrate options of ezselection fieldType

### ISSUE THREAD

**Issue by ericlery** [kaliop-uk/ezmigrationbundle#89]
Any doc for how to migrate options of ezselection fieldType ?

**Comment by gggeek** [comment]
Sorry, I forgot to add some docs for this for the 3.2 release.

However, if you upgrade to version 3.2, you can probably find out by yourself what you need:
- have a ContentType which has a field of type ezselection
- use the enhanced 'generate' command to create a migration which describes that ContentType: it should include the selection options in its field definition
- play around with that information until you get the change that you need

Do not hesitate to post here any negative results if you still can not make it.

**Comment by gggeek** [comment]
docs added in version 3.2.1
