### ISSUE TITLE
Undefined index: eng-GB when creating migration from existing content type

### ISSUE THREAD

**Issue by RandyCupic** [kaliop-uk/ezmigrationbundle#95]
When I try to create migration file from existing content type, I'm getting this error

> [Symfony\Component\Debug\Exception\ContextErrorException]  
  Notice: Undefined index: eng-GB

I specify the "lang" parameter when I run the generate command but it seems that it's not being used at all. After further inspecting, it seems that method setLanguageCode() in RepositoryExecutor is never being called so it will always return the default eng-GB language.

I fixed this by calling the setLanguageCode() command to set the language to the one specified in --lang parameter.

**Comment by gggeek** [comment]
thx, will try to fix within the week

**Comment by gggeek** [comment]
released
